### ISSUE TITLE
404 on Bindle downloads

### ISSUE THREAD

**Issue by vdice** [deislabs/bindle#320]
I'm getting a 404 attempting to download bindle binaries (have been trying the [v0.8.0](https://github.com/deislabs/bindle/releases/tag/v0.8.0) release).

For example:

```
$ curl -v https://bindle.blob.core.windows.net/releases/bindle-v0.8.0-macos-amd64.tar.gz -o bindle 2>&1 | tail -n15
> User-Agent: curl/7.77.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 The specified blob does not exist.
< Content-Length: 215
< Content-Type: application/xml
< Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
< x-ms-request-id: 36dc4ef3-e01e-0025-4169-2ed8a1000000
< x-ms-version: 2009-09-19
< Date: Wed, 02 Mar 2022 19:12:49 GMT
<
{ [215 bytes data]
100   215  100   215    0     0    816      0 --:--:-- --:--:-- --:--:--   833
* Connection #0 to host bindle.blob.core.windows.net left intact

$ cat bindle
<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:0ade094f-201e-0015-3c69-2e666e000000
Time:2022-03-02T19:13:06.5102032Z</Message></Error>
```

**Comment by radu-matei** [comment]
Same here, I'm getting 404s for all releases.

**Comment by squillace** [comment]
well, now, that's interesting. Lemme look.

**Comment by squillace** [comment]
did anyone modify a GH action here anytime recently, because there are no releases in the blob store, only canaries

**Comment by radu-matei** [comment]
ref #319

**Comment by bacongobbler** [comment]
This one's on me. 😞 

The github action fetches the latest version of the CLI. There was a short window of ~10 minutes this afternoon where the `sync` flag for `azure-blob-storage-upload` was always enabled because of some changes. When sync is enabled, `az sync` attempts to "synchronize" the remote state with the local state... If the local state did not have the old release assets, `az sync` deleted them.

I fixed it as quickly as I could, but y'all seem to have been caught in the blast.

Here's the action run that purged the container:

https://github.com/deislabs/bindle/runs/5395617703?check_suite_focus=true#step:7:319

https://github.com/deislabs/bindle/pull/319 pins us to v2.0.0 to prevent this situation from happening again.

We should be able to re-run the github action from each git tag to re-release the assets. If not, I'd be happy to assist and figure out a solution.

**Comment by bacongobbler** [comment]
I managed to restore bindle v0.8.0, v0.7.1, and v0.7.0. I'll work through restoring the older releases, but that should get you back up and running again. Thanks for your patience!

**Comment by vdice** [comment]
Thank you @bacongobbler!  Closing.

**Comment by radu-matei** [comment]
Thank you so much for solving this, @bacongobbler!

**Comment by bacongobbler** [comment]
Re-opening... Seems like the bindle uploads are gone again.

Now that #319 has been merged, hopefully this has been fixed moving forward.

**Comment by bacongobbler** [comment]
Builds are back, and the sync option is disabled. Following up in https://github.com/deislabs/bindle/pull/324 to fix canary builds not uploading.
